### PR TITLE
removed old stuff and boilerplate from sample project app delegate

### PR DESCRIPTION
**Pull request by seanwolter**
removed old stuff and boilerplate from sample project app delegate

### CODE REVIEW

**Comment by seanwolter** [comment]
@chillpop Could you take a quick look before I tag 1.1.7 for cukopods?

**Comment by chillpop** [comment]
looks good to me

**Comment by vokal-isaac** [comment]
You're adding new methods in the new version, right?  Changing any existing methods?

**Comment by seanwolter** [comment]
@vokal-isaac Documentation and new methods only in the new version.

**Comment by vokal-isaac** [comment]
With new methods, maybe v1.2.0?

**Comment by seanwolter** [comment]
/me google semantic versioning
Yes, @vokal-isaac you are correct this should be 1.2.0

**Pull request merged**
