### PR TITLE
Use xUnique for example projects

### PR DESCRIPTION
**Pull request by chillpop**
Use xUnique for example projects to make project file diffs easier to handle going forward.

@vokal/ios-developers, @seanwolter "code" review?

### CODE REVIEW

**Comment by designatednerd** [comment]
Seems legit to me pending Travis

**Comment by designatednerd** [comment]
@chillpop I think you have to uncheck and recheck the test targets in the test bit of the scheme because the identifiers changed

**Comment by chillpop** [comment]
updated

**Comment by seanwolter** [comment]
I have no opinion about xUnique. Look cool :sunglasses:

**Comment by vokal-isaac** [comment]
@seanwolter You should have an opinion about it and your opinion should be that it's a good thing.  https://github.com/truebit/xUnique

**Comment by vokal-isaac** [comment]
(:goat:,)

**Pull request merged**
