### PR TITLE
Initial project setup for swift example

### PR DESCRIPTION
**Pull request by chillpop**
@vokal/ios-developers, I'm adding an example project in swift.  This is the initial setup and results of `pod install`.  Review please?

### CODE REVIEW

**Comment by brockboland** [comment]
I like your gumption. LGTM

**Comment by brockboland** [comment]
I don't think Travis will have an issue with this but waiting just in casies

**Comment by chillpop** [comment]
Travis isn't even set up to compile/run this yet but it's good to make sure I didn't break anything.

**Comment by brockboland** [comment]
Travis works in mysterious ways and none of us can claim to divinate his intentions.

Divinate is a word right?

**Pull request merged**
