### PR TITLE
Allow use in app extensions

### PR DESCRIPTION
**Pull request by chillpop**
To allow Vokoder to be used in app extensions, some small parts had to be removed.  Specifically, the parts that call `[UIApplication sharedApplication]` and `UIAlertView`/`UIAlertController`.  To achieve this, I added a new subspace that handles the nitty gritty of adding a new preprocessor definition that we can use.  (Apple did not expose any way that I can tell to alert the compiler that it is compiling for an app extension.)  Without this, Vokoder would fail to build when included in an app extension target.

I added a new today extension target that will be built on Travis to verify that there are no errors. (Thus the giant diff.)

@brockboland, @vokal-isaac, @bryanluby, @designatednerd code review?

### CODE REVIEW

**Comment by chillpop** [comment]
Looks like I need to add some tests for the new target to make Travis happy.

**Comment by chillpop** [comment]
Change of plans: build the Today Widget target along with the main sample app target.

**Comment by brockboland** [comment]
@chillpop are you using `VOKMigrationFailureOptionWipeRecoveryAndAlert` in your project?

@seanwolter @designatednerd @vokal-isaac @bryanluby quick poll: has **anyone** ever used `VOKMigrationFailureOptionWipeRecoveryAndAlert` on a project? Can we just remove it? It seems unlikely that many projects would tell the user about this error, particularly with a non-localized alert. Removing it would complicate release versioning on the 3.x branch, to be sure, but this seems like an unnecessary workaround for a feature that probably isn't used.

**Comment by chillpop** [comment]
I've never used it.  I really like that idea.

**Comment by brockboland** [comment]
Looks like that option was originally added in https://github.com/vokal/VOKCoreDataManager/commit/82f8d8c13687021da411b02a39f9ee877642ea62, maybe written by @mattfoley? Commit message is unclear.

Hey @mattfoley: do you still use this, and if so, do you still use `VOKMigrationFailureOptionWipeRecoveryAndAlert`?

**Comment by chillpop** [comment]
🕵️ @brockboland

**Comment by bryanluby** [comment]
@brockboland I have not used it

**Comment by MattFoley** [comment]
Used it for years, although on a slightly modified branch of the original CoreDataManager-iOS repository.

**Comment by MattFoley** [comment]
Oh sorry, never mind, I just used the wipe silently option.

**Comment by MattFoley** [comment]
Feel free to remove it, I'm spending all my days in React Native lately, no more Core Data stuggles.

**Comment by brockboland** [comment]
Groovy, thanks @MattFoley!

**Comment by brockboland** [comment]
LGTM

**Pull request merged**
