### PR TITLE
Max Bare is a God Among Men

### PR DESCRIPTION
**Pull request by designatednerd**
Addresses #2

### CODE REVIEW

**Comment by designatednerd** [comment]
@vokal/ios-developers Max has left us with a lovely parting gift of a kick-ass logo for Vokoder. What say ye? (cc original requestor @seanwolter)

**Comment by brockboland** [comment]
yessssssssss

**Comment by naomihimley** [comment]
SIQ

**Comment by vokal-isaac** [comment]
:shipit:

**Comment by bryanluby** [comment]
:100:

**Comment by designatednerd** [comment]
Takin' all that as a yes.

**Comment by seanwolter** [comment]
It's really happening.

**Pull request merged**
